### ISSUE TITLE
Rifthook bug

### ISSUE THREAD

**Issue by Hackerlol2** [basedproperty/Rifthook#1]
If you stay on visuals to much it'll not go on any other tab it'll stay on visual then you cant go on rage of misc or any other tab on the gui its annoying you have to rejoin the server

**Comment by basedproperty** [comment]
Were you on a color picker?

**Comment by Hackerlol2** [comment]
whats that?

**Comment by basedproperty** [comment]
where you click on a color and set the color of something

**Comment by Hackerlol2** [comment]
No

**Comment by basedproperty** [comment]
was there anything else apart from staying on the visuals tab too long so i can replicate this issue?

**Comment by Hackerlol2** [comment]
No not really expect when you choose to many visual scripts

**Comment by basedproperty** [comment]
I am unable to replicate this bug. If I can replicate it properly in the near future, I will probably fix it.
