### ISSUE TITLE
ESP Bug

### ISSUE THREAD

**Issue by Boxstar3D** [basedproperty/Rifthook#4]
![image](https://user-images.githubusercontent.com/97264166/148471823-ad80af81-117e-47d5-831d-1e2da2cc026f.png)
ESP is very bugged, and the backtracked person on screen is alive.

**Comment by basedproperty** [comment]
Does the ESP still move, or it just stuck there?

**Comment by basedproperty** [comment]
After further investigation, this was actually an issue with Synapse. Nothing I can do about it.
