### ISSUE TITLE
no horse speed changer, aimbot issue

### ISSUE THREAD

**Issue by ghost** [basedproperty/Rifthook#5]
no horse speed changer. Aimbot doesn't work with wallcheck on. Trigger bot doesn't work. Everything else is good. Good script.

**Comment by basedproperty** [comment]
Horse speed changes is currently only in the Developer build. It has not been published to the Beta/Public builds.
Wallcheck required that the player you are aimbotting is visible.
Triggerbot is broken and will be removed in 3.7.7 or 3.8.
